### ISSUE TITLE
Doesn't compile when targeting `aarch64-apple-darwin`

### ISSUE THREAD

**Issue by Jake-Shadle** [NVIDIA-Omniverse/PhysX#107]
### Library and Version

5.1.3

### Operating System

aarch64-apple-darwin

### Steps to Trigger Behavior

 1. Try to compile for `aarch64-apple-darwin`
 2. Failure

### Code Snippet to Reproduce Behavior

Irrelevant

### Expected Behavior

PhysX compiles

### Actual Behavior

PhysX fails to compile for several reasons:

1. FdUnixFPU.cpp includes `<xmmintrin.h>` if `PX_OSX` is 1, which fails since that is an x86 only header. See https://github.com/EmbarkStudios/PhysX-5/commit/1e04de172913760b09227111153b84f56805ade9 for a commit to fix this
2. SIMD is not properly enabled in PxVecMath.h, causing failures in other code that doesn't have the same guard. See https://github.com/EmbarkStudios/PhysX-5/commit/33e5eb7423a20bede0f933d9fdf3dc3d5e07fe72 for a commit to fix this.
3. SnSerialUtils.cpp fails to compile due to no case matching aarch64 and OSX, resulting in [`Unknown binary platform`](https://github.com/NVIDIA-Omniverse/PhysX/blob/93b6c250e2141f8e87543bc8bb763046f26ffbc5/physx/source/physxextensions/src/serialization/SnSerialUtils.cpp#L93). See https://github.com/EmbarkStudios/PhysX-5/commit/720c8a5d2bffc462a5c19b9c5dc0e8d99aaf5af3 for a patch to fix this.

FYI, the only reason that PhysX 4.1 compiled for `aarch64-apple-darwin` was because it misidentified the target to `PX_IOS`

https://github.com/NVIDIAGameWorks/PhysX/blob/a2c0428acab643e60618c681b501e86f7fd558cc/pxshared/include/foundation/PxPreprocessor.h#L103-L106

But it appears like iOS support has been completely dropped in PhysX 5 (with no CHANGELOG entry) resulting in these errors.

**Comment by preist-nvidia** [comment]
Hi @Jake-Shadle - we are not supporting this build platform, but you may contribute/find support for it on the community-maintained build config fork: https://github.com/NVIDIA-Omniverse/PhysX#community-maintained-build-configuration-fork
