### ISSUE TITLE
Different integration behavior of eLOCK_ANGULAR and eLOCK_LINEAR flags

### ISSUE THREAD

**Issue by Tooflevor** [NVIDIA-Omniverse/PhysX#108]
### Library and Version
Example: PhysX v5.1.2

### Operating System
Windows 10

### Steps to Trigger Behavior

 1. Lock all axes of dynamic object with 
 ```cpp
setRigidDynamicLockFlags(PxRigidDynamicLockFlag::eLOCK_LINEAR_X | PxRigidDynamicLockFlag::eLOCK_LINEAR_Y |
                          PxRigidDynamicLockFlag::eLOCK_LINEAR_Z | PxRigidDynamicLockFlag::eLOCK_ANGULAR_X | 
                          PxRigidDynamicLockFlag::eLOCK_ANGULAR_Y | PxRigidDynamicLockFlag::eLOCK_ANGULAR_Z)
```
 2. set non-zero linear and angular velocity for object

### Code Snippet to Reproduce Behavior

```cpp
PxReal halfExt = 2.0f;
PxRigidDynamic* body = gPhysics->createRigidDynamic(PxTransform(PxVec3(0.0f, halfExt, 0.0f)));
PxShape* shape = gPhysics->createShape(PxBoxGeometry(halfExt, halfExt, halfExt), *gMaterial);
body->attachShape(*shape);
shape->release();
PxRigidBodyExt::updateMassAndInertia(*body, 10.0f);
gScene->addActor(*body);

body->setRigidDynamicLockFlags(PxRigidDynamicLockFlag::eLOCK_LINEAR_X | PxRigidDynamicLockFlag::eLOCK_LINEAR_Y |
                               PxRigidDynamicLockFlag::eLOCK_LINEAR_Z | PxRigidDynamicLockFlag::eLOCK_ANGULAR_X | 
                               PxRigidDynamicLockFlag::eLOCK_ANGULAR_Y | PxRigidDynamicLockFlag::eLOCK_ANGULAR_Z);
body->setLinearVelocity(PxVec3(0.0f, 1.0f, 0.0f));
body->setAngularVelocity(PxVec3(0.0f, PxPiDivFour, 0.0f));
body->setLinearDamping(0.0f);
body->setAngularDamping(0.0f);
body->setActorFlags(PxActorFlag::eDISABLE_GRAVITY);
```

### Expected Behavior

Body is not moving and rotating or body is moving and rotating

### Actual Behavior

Body is moving but not rotating.

### Possible cause
In code block https://github.com/NVIDIA-Omniverse/PhysX/blob/93b6c250e2141f8e87543bc8bb763046f26ffbc5/physx/source/lowleveldynamics/src/DyRigidBodyToSolverBody.cpp#L75-L80 possibly should be used `lin` variable instead of `data.linearVelocity`.

**Comment by PierreTerdiman** [comment]
Yes we recently fixed this. I think it was working with TGS, but not with PGS.

Look for this function in DyBodyCoreIntegrator.h and add the highlighted lines:


PX_FORCE_INLINE void integrateCore(PxVec3& motionLinearVelocity, PxVec3& motionAngularVelocity, 
	PxSolverBody& solverBody, PxSolverBodyData& solverBodyData, PxF32 dt, PxU32 lockFlags)
{
	if (lockFlags)
	{
		if (lockFlags & PxRigidDynamicLockFlag::eLOCK_LINEAR_X)
		{
			motionLinearVelocity.x = 0.f;
			solverBody.linearVelocity.x = 0.f;
			**solverBodyData.linearVelocity.x = 0.f;**
		}
		if (lockFlags & PxRigidDynamicLockFlag::eLOCK_LINEAR_Y)
		{
			motionLinearVelocity.y = 0.f;
			solverBody.linearVelocity.y = 0.f;
			**solverBodyData.linearVelocity.y = 0.f;**
		}
		if (lockFlags & PxRigidDynamicLockFlag::eLOCK_LINEAR_Z)
		{
			motionLinearVelocity.z = 0.f;
			solverBody.linearVelocity.z = 0.f;
			**solverBodyData.linearVelocity.z = 0.f;**
		}

That should fix it.
