### ISSUE TITLE
Solution Generation and Building doesn't work in folders which contain spaces

### ISSUE THREAD

**Issue by thempc** [NVIDIA-Omniverse/PhysX#116]
### Library and Version
PhysX v5.1.3

### Operating System
Windows 11

### Steps to Trigger Behavior
 1. Extract a release into a folder in windows constaining a space, like "C:/Test Folder"
 2. Try to follow normal build/generate/compile instructions
 3. Everything fails due to (I assume CMake or python scripts) not handling a space in a folder

### Code Snippet to Reproduce Behavior
No code required.

### Expected Behavior
To be able to put this on a users machine, inside a folder which contains a space, and that it works.

### Actual Behavior
It won't build solutions, and it isn't possible to generate solutions in another folder and then copy them over due to how everything is hardlinking everything else instead of using $(SolutionDir) and relative paths.

**Comment by ayoub-belarbi** [comment]
Hello @thempc,

Indeed, it's a bug.
I have fixed the issue and it should be included in the next release.
Until then, I will appreciate it if you can use a path that doesn't contain any space.

Thanks
