### ISSUE TITLE
external/cmakemodules is missing in PhysX 5

### ISSUE THREAD

**Issue by jjiangweilan** [NVIDIA-Omniverse/PhysX#127]
I am building physx from CMake (the .cmake in physx/compiler/public). The cmake file needs `CMAKEMODULES_PATH` which is used to be find in the `Physx/externals/`. After upgrading to PhysX 5, all the externals are removed. How should I build the project with cmake now

**Comment by ayoub-belarbi** [comment]
Hello @jjiangweilan,
You will build exactly the same way. The difference from before is that the dependencies which use to be stored in the externals folder are now hosted on S3 and downloaded when you first generate the project. From the user point of view, nothing changed.
Thanks
