### ISSUE TITLE
Library name on Android build

### ISSUE THREAD

**Issue by MarkaRagnos0815** [NVIDIA-Omniverse/PhysX#160]
I have managed to build Physx libraries for Android (latest main branch and based on O3DE). I managed to build Android versions under Windows and Linux and for armebi-v7a, arm64-v8a, x86 and x86_64 too. When I build everything under Windows the libs names contains a _64 for 64 bit builds and _32 for 32 bit builds. On Linux all libs on all archs does have _32 in it's file name. I didn't found in the cmake structure where the name is generated. 

Where is the place to modify the cmake files to have the same output names generated as on windows?

**Comment by preist-nvidia** [comment]
@MarkaRagnos0815 sorry for the very late response - please reopen this if you did not find the place in the cmake in the meantime.
