### ISSUE TITLE
Impossible to build PhysX

### ISSUE THREAD

**Issue by Moi78** [NVIDIA-Omniverse/PhysX#184]
### Library and Version
PhysX v5.2.1

### Operating System
Linux/Kubuntu 23.04. Clang 15.0.7 // CMake 3.25.1

When I tried to compile PhysX, using the given script and doing a `make all -j15`, the compiler gives me a bunch of error such as : `/media/mathis/Data2/PhysX/physx/source/lowlevel/software/src/PxsCCD.cpp:1748:8: error: variable 'totalActivePairs' set but not used [-Werror,-Wunused-but-set-variable]`. It makes the project impossible to build and the build system is too obscure to me to investigate how do deactivate warnings as errors.

**Comment by preist-nvidia** [comment]
Hi @Moi78 ,

Please have a look at the supported platform/compiler versions here: https://github.com/NVIDIA-Omniverse/PhysX/blob/main/physx/documentation/platformreadme/linux/README_LINUX.md

Using other platform/compiler versions likely requires CMAKE changes, yes.

Another great option is to consider using the vcpkg port: https://omni-101.github.io/omniverse/2023/07/07/omniverse-physx-vcpkg-port/

Philipp
