### ISSUE TITLE
Crash / invalid read inside Sc::Scene::beforeSolver

### ISSUE THREAD

**Issue by Elercia** [NVIDIA-Omniverse/PhysX#211]
### Library and Version
PhysX v5.3.0 (last commit on trunk)

### Operating System
Windows 10

### Steps to Trigger Behavior
1. Add a dynamic rigid body
3. Add a force to this rigidbody
5. Release this rigidbody
7. Do a simulation step

This repro step will trigger an invalid read / crash inside the method ``Sc::Scene::beforeSolver`` when accessing the member ``mCore`` that was invalidated inside the step 3 (because it was registered inside ``sc::Scene::mVelocityModifyMap`` at step 2)
``retainsAccelerations = (body->mCore->mFlags & PxRigidBodyFlag::eRETAIN_ACCELERATIONS);``

### Code Snippet to Reproduce Behavior
This code sample is based on the file ``SnippetHelloWorld.cpp`` and can be placed inside the ``InitPhysics`` function.
It reproduce the bug with a repro rate of 100%.

```cpp
PxRigidDynamic* spherePhysic = PxCreateDynamic( *gPhysics, PxTransform( 0.f, 0.f, 0.f ), PxSphereGeometry( 3.0f ), *gMaterial, 1.f );
spherePhysic->setRigidBodyFlag( PxRigidBodyFlag::eRETAIN_ACCELERATIONS, true );// This flag is not useful as is but it invalidate the solution that is releasing actors after the step is done
gScene->addActor( *spherePhysic );

// Add force will register spherePhysic node index into sc::Scene::mVelocityModifyMap
spherePhysic->addForce( PxVec3( 1.f, 1.f, 2.f ) );

// Delete pointers (return memory to allocator)
// This will destroy member NpRigidDynamic::mCore
// This will also remove actors from gScene
spherePhysic->release();

// Step
// This will crash/access freed memory of NpRigidDynamic::mCore inside Sc::Scene::beforeSolver
gScene->simulate( 1.0f / 60.0f );
gScene->fetchResults( true );
```

You may need to invalidate memory of ``Sc::BodyCore`` to better visualize the issue :
```cpp
Sc::BodyCore::~BodyCore()
{
    PX_ASSERT(getSim() == 0);
    memset( this, 0xFF, sizeof( BodyCore ) );
}
```

### Expected Behavior
When removing a actor from a scene, the cached state concerning this actor should be cleared. 

### Actual Behavior
Crash.

**Comment by preist-nvidia** [comment]
Thank you for the excellent bug report Vincent! We'll have a look!

**Comment by preist-nvidia** [comment]
Internal tracking: PX-4603

**Comment by adenzler-nvidia** [comment]
Thanks for the report! I was able to reproduce the issue and can confirm that we are not cleaning up that state, which is problematic. The fix is very simple and will appear in PhysX 5.3.1.

In the meantime, you can add the snippet 

```
if (!isArticulationLink())
	scene.getVelocityModifyMap().boundedReset(mNodeIndex.index()); 
```

to the destructor of ScBodySim to work around the issue.

**Comment by preist-nvidia** [comment]
This is in 5.3.1 FYI.
