### ISSUE TITLE
PxCustomGeometryExt::BaseConvexCallbacks::raycast doesn't report back which fields are valid

### ISSUE THREAD

**Issue by goncalo** [NVIDIA-Omniverse/PhysX#256]
### Library and Version
PhysX v5.1.0

### Operating System
Example: Windows 10

### Steps to Trigger Behavior
 1. raycast against cone or cylinder custom shapes
 2. although the query always returns valid position & normal, the hitFlags do not reflect that

**Comment by 7zx** [comment]
Hello @goncalo This was the only way for me to reach out to you. Would you be available for a chat? I have a proposal I'd like to discuss with you.

**Comment by vreutskyy** [comment]
Will be fixed in the next release. Thanks
