### ISSUE TITLE
I can not link physx 5.3.0 library from vcpkg into my project

### ISSUE THREAD

**Issue by ChivenZhang** [NVIDIA-Omniverse/PhysX#275]
### Library and Version

PhysX v5.3.0 from vcpkg

### Operating System

Windows 11, visual studio 2022, v142 toolset

### Steps to Trigger Behavior

 1. install physx:x64-windows using vcpkg
 2. link 15 libs into project
 3. compile failed as lnk2019 error

### Code Snippet to Reproduce Behavior

![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/48938612/e6429c0a-bab2-4c20-be49-539f6ce55156)

![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/48938612/b9b01944-3c70-4241-8c7f-9e36ec33256f)

![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/48938612/b748d595-6720-472c-8e9b-ff4b5b0f7899)

![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/48938612/07e6664c-7e81-4346-99f1-01c9b6a2c4fc)

### Expected Behavior

compile pass

### Actual Behavior

compile failed

![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/48938612/6e01d337-5d8f-47b8-814c-1781a36ab058)

**Comment by preist-nvidia** [comment]
Hi @ChivenZhang - if you follow the instructions here, does it work? https://omni-101.github.io/omniverse/2023/07/07/omniverse-physx-vcpkg-port/

**Comment by ChivenZhang** [comment]
It do works, Thanks. But I wonder why I can not use physx in ordinary way, just install the library and link it.

**Comment by preist-nvidia** [comment]
Hi @ChivenZhang - sorry we cannot help with linker/build config beyond pointing you to the unofficial vcpkg port docs.
