### ISSUE TITLE
Stage Properties crashes Flow exampple

### ISSUE THREAD

**Issue by cbertin1932** [NVIDIA-Omniverse/PhysX#28]
For PhysX Flow 5.1.0 on my Windows 10, when I click the Stage Properties in the Flow example, the thing thing crashes. Error, if I have no break points points the the problem being line 4781 in imgui.cpp.

**Comment by areidmeyer** [comment]
I was able to reproduce an imgui assert in the debug build. Will see about a fix.
It is not a crash proper though, behavior is fine in release build.

**Comment by preist-nvidia** [comment]
Fixed in Flow 2.0.2 release.
