### ISSUE TITLE
D6 Joint doesn't report drive force

### ISSUE THREAD

**Issue by kermado** [NVIDIA-Omniverse/PhysX#286]
It looks like the drive force isn't reported for some joints. In particular, the D6 joint doesn't report the drive force/torque. Force reporting is only enabled for locked axes. I can't see any way to enable drive force reporting without modifying the source code.

Would it be possible to add a flag to `PxD6JointDriveFlag` or similar? This could then be used to set the `Px1DConstraintFlag::eOUTPUT_FORCE` in `ConstraintHelper::addDrive()`.

**Comment by vreutskyy** [comment]
Hi @kermado 
Thanks for the reporting this issue. We'll check it.

**Comment by preist-nvidia** [comment]
@kermado - can you use an articulation instead? We do have https://nvidia-omniverse.github.io/PhysX/physx/5.4.0/docs/Articulations.html#link-incoming-joint-force

And if you project this onto the DOF, you'll get the drive force (plus friction/limits if they are active).

**Comment by kermado** [comment]
@preist-nvidia I can in most cases, but sometimes we have cycles that need to be broken and we still need to measure forces/torques for those joints. At the moment, I have made the changes described, which allows me to get these values out.

**Comment by preist-nvidia** [comment]
Understood - would you mind creating a PR for the changes and we can look at the code and consider integrating it?

**Comment by msauter-nvidia** [comment]
Update: support for adding the drive forces is planned to go into release 5.5.0-106.2. Look for PxD6JointDriveFlag::eOUTPUT_FORCE
