### ISSUE TITLE
PhysXFoundation_64.dll was not found

### ISSUE THREAD

**Issue by mishaBogdanov** [NVIDIA-Omniverse/PhysX#292]
Hello, I'm using visual studio 2022 to link to physX. here are all the settings I've changed:

![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/78181954/36e0e8e9-f2e9-4126-a2f4-ccb307fd7670)
![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/78181954/8b7d2b26-44a5-4294-87c3-6ce4d9d09a8b)
![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/78181954/efff6b00-4971-4bc1-bc75-e9eca8a8b412)
![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/78181954/f1da67ff-ce04-48d2-9586-a8452f3d890f)
the .dll seems to be there in my checked folder:
![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/78181954/2d0769e1-45ec-4f23-9a33-3bde4012922e)
the code that's giving me issues is

PxDefaultErrorCallback	gErrorCallback;

without it my code compiles. 

below is the error that I get when I try to run:

![image](https://github.com/NVIDIA-Omniverse/PhysX/assets/78181954/3618f435-4319-4c7a-9461-1628127dfa9a)

all other visual studio settings should be at default, as I reset them all in attempt to fix this issue. my steps to get to this point are 
- download physX
- run generate_projects.bat
- run the visual studio solution that's generated in checked mode
- the snippets work
- start a new project with the above settings.

Any help appreciated, Thanks!!

**Comment by vreutskyy** [comment]
Hi @mishaBogdanov 
Did you try to copy PhysX DLLs next to your project's executable? I mean the folder your EXE file is in.

**Comment by mishaBogdanov** [comment]
Thank-you so much, this fixed all my issues.
