### ISSUE TITLE
In the PxCooking stage, are collinear triangles removed?

### ISSUE THREAD

**Issue by szhang21** [NVIDIA-Omniverse/PhysX#315]
In the PhysX 5.1.3 documentation, it is mentioned: "Mesh cleaning removes invalid triangles (containing out-of-range vertex references), duplicate triangles, and zero-area triangles." However, the baked triangle data still includes collinear triangles.

**Comment by szhang21** [comment]
I am sure I did not set PxMeshPreprocessingFlag::eDISABLECLEANMESH.

**Comment by vreutskyy** [comment]
Hi @szhang21 
Thanks for the report, we'll check this. It would help if you could provide some sample/data to reproduce the issue.

**Comment by szhang21** [comment]
Hello, I have checked, and this issue has been resolved in the latest version of PhysX. In PhysX 5.1.3, the condition being checked is area2==0.0f. The value 0.0f is not sufficient to ensure that the area of the transformed triangle remains 0, leading to the assert failure in disconnection.Thank you for your reply
