### ISSUE TITLE
Modify CMakeModules package Packman downloads to include Android, iOS and Mac platforms

### ISSUE THREAD

**Issue by moraaar** [NVIDIA-Omniverse/PhysX#59]
The name of the bin folders will be incorrect when building for Android, iOS and Mac-arm64. 

**To fix this nVidia has to modify the CMakeModules package it's downloaded from packman when building PhysX, since it's not part of the Github repo**. 

The file that needs to be modified is `GetCompilerAndPlatform.cmake`, changing the `if` condition inside `GetPlatformBinName` function to this:

````
	ELSEIF(TARGET_BUILD_PLATFORM STREQUAL "mac")
		IF(${PX_OUTPUT_ARCH} STREQUAL "x86")
			SET(RETVAL "mac.x86_${LIBPATH_SUFFIX}")
		ELSEIF(${PX_OUTPUT_ARCH} STREQUAL "arm")
			SET(RETVAL "mac.arm64")
		ENDIF()
	ELSEIF(TARGET_BUILD_PLATFORM STREQUAL "ios")
		SET(RETVAL "ios.arm_${LIBPATH_SUFFIX}")
	ELSEIF(TARGET_BUILD_PLATFORM STREQUAL "android")
		SET(RETVAL "android.${ANDROID_ABI}")
````

This code modification was tested locally on these PRs: https://github.com/NVIDIA-Omniverse/PhysX/pull/40 https://github.com/NVIDIA-Omniverse/PhysX/pull/49 https://github.com/NVIDIA-Omniverse/PhysX/pull/51

**Comment by MarkaRagnos0815** [comment]
how is the status here. It would be nice to have this functionality

**Comment by preist-nvidia** [comment]
@moraaar - @ayoub-belarbi removed the cmake modules dep with 5.2.1 and they are now included into the repo: https://github.com/NVIDIA-Omniverse/PhysX/tree/main/physx/source/compiler/cmake/modules

**Comment by ayoub-belarbi** [comment]
As @preist-nvidia mentioned. The modules are no longer an external Packman dependency. Feel free to fork/modify as you wish.
Thanks
