### ISSUE TITLE
Add to packman the arm-based version of python for Mac

### ISSUE THREAD

**Issue by moraaar** [NVIDIA-Omniverse/PhysX#60]
Python package used by packman on Mac is always the x86_64 architecture one and when trying to build with an arm-based Mac it generates the error `dyld[number]: missing symbol called`. 

**To fix this nVidia has to add an ARM python package for mac into the packman scripts** here https://github.com/NVIDIA-Omniverse/PhysX/blob/release/104.1/physx/buildtools/packman/packman#L81-#L82 to something like this:

````
	if [ $PLATFORM == 'Darwin' ] && [ $PROCESSOR == 'x86_64' ]; then
		PYTHON_PACKAGE=$PYTHON_VERSION-macos-x86_64
	elif [ $PLATFORM == 'Darwin' ] && [ $PROCESSOR == 'arm64' ]; then
		PYTHON_PACKAGE=$PYTHON_VERSION-macos-arm64  # This package doesn't exist at the moment, NVIDIA has create it and make it available to fetch from S3.
````

**Temporary Workaround**
As a temporary solution, you can use your system's python by adding the environment variable `PM_PYTHON_EXT` before building, for example by adding `export PM_PYTHON_EXT="python3"` into your `.bash_profile` file.

Related PR: https://github.com/NVIDIA-Omniverse/PhysX/pull/51

**Comment by preist-nvidia** [comment]
Done in o3de fork.
