### ISSUE TITLE
generate_projects downloads bootstrap packages without TLS

### ISSUE THREAD

**Issue by chloekek** [NVIDIA-Omniverse/PhysX#7]
### Library and Version

Release 104.0.

### Operating System

Any.

### Steps to Trigger Behavior

 1. Run build script.
 2. Observe that TLS is not used to connect to bootstrap.packman.nvidia.com.

### Code Snippet to Reproduce Behavior

```
$ bash generate_projects.sh linux
```

### Expected Behavior

Build script connects to bootstrap.packman.nvidia.com over TLS.

### Actual Behavior

Build script connects to bootstrap.packman.nvidia.com without TLS, allowing an attacker to replace python and packman-common with malicious versions. Ideally, the build script would also verify checksums after downloading files.

**Comment by amoravanszky** [comment]
Thank you for this submission, we will look into changing packman to use https for the next release.
