### ISSUE TITLE
Negative TOI calculation problem for Convex- TriangleMesh CCD

### ISSUE THREAD

**Issue by pkusilence** [NVIDIA-Omniverse/PhysX#86]
![企业微信截图_16759133925174](https://user-images.githubusercontent.com/42665265/217710748-8e89670f-860e-4a5a-934e-e16af2fd4568.png)

https://github.com/NVIDIA-Omniverse/PhysX/blob/release/104.1/physx/source/geomutils/src/ccd/GuCCDSweepConvexMesh.cpp

In GuCCDSweepConvexMesh.cpp, Line 555 to Line 584, it is calculating the penetration if TOI < 0 after SweepShapeTriangle. However, the distanceSq makes me confused. Since sphereCenterInTransform1 is always identity （trimesh must be static). So the distance is from triangle mesh vertex space origin to the hit triangle, but it is arbitrary，since triangle mesh vertex space origin can be anywhere. So the TOI (negative means penetration) might be wrong in this case.

There are still other problems:
1. SweepAnyShapeHeightfield seems to be more reasonable but  sphereCenterInTr1 and sphereCenterInTr1T0 is the same. 
2. Line 310 & 576 is opposite (dd > d or dd < d ?).
3. The "res = -(2.f * inSphereRadius - distance)" looks strange too, I cannot find its geometrical interpretation.

**Comment by preist-nvidia** [comment]
Hi @pkusilence - sorry, we dropped the ball here, my bad.

Did you figure out more in the mean time or would it be helpful if we had a closer look still?

Internal tracking: PX-4673

**Comment by preist-nvidia** [comment]
Closing for now until further comments are made.

**Comment by pkusilence** [comment]
> Hi @pkusilence - sorry, we dropped the ball here, my bad.
> 
> Did you figure out more in the mean time or would it be helpful if we had a closer look still?
> 
> Internal tracking: PX-4673

I choosed to skip all the things PhysX done for negative TOI, the simulation looks fine now. Thanks for your reply!
