### ISSUE TITLE
[License.md] License clarification

### ISSUE THREAD

**Issue by DistantThunder** [NVIDIA-Omniverse/PhysX#9]
Hello,

I'm always happy for proprietary tech to become fully FLOSS but some people noticed a potential conflict between:

* https://github.com/NVIDIA-Omniverse/PhysX/blob/80c0aab63e67fcc269c849bbfc2ac76bee4a129a/LICENSE.md
* And the BSD license evoked in the Readme.

Could you clarify?

**Comment by Calinou** [comment]
This looks like a 3-clause BSD license to me: https://opensource.org/licenses/BSD-3-Clause
